name: zqg-indextts
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - expat=2.7.3
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.11.14
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - accelerate==1.8.1
      - aiofiles==24.1.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - argbind==0.3.9
      - asttokens==3.0.1
      - audioread==3.1.0
      - brotli==1.2.0
      - cachetools==6.2.2
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - chumpy==0.70
      - click==8.3.1
      - cn2an==0.5.22
      - contourpy==1.3.3
      - cycler==0.12.1
      - cython==3.0.7
      - decorator==5.2.1
      - deepspeed==0.17.1
      - descript-audiotools==0.7.2
      - distance==0.1.3
      - docstring-parser==0.17.0
      - einops==0.8.1
      - executing==2.2.1
      - fastapi==0.122.0
      - ffmpeg-python==0.2.0
      - ffmpy==1.0.0
      - filelock==3.20.0
      - fire==0.7.1
      - flash-attn==2.8.3
      - flatten-dict==0.4.2
      - fonttools==4.60.1
      - fsspec==2025.10.0
      - future==1.0.0
      - g2p-en==2.1.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-auth==2.43.0
      - google-auth-oauthlib==0.4.6
      - gradio==5.45.0
      - gradio-client==1.13.0
      - groovy==0.1.2
      - grpcio==1.76.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - hjson==3.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - imageio==2.37.2
      - imageio-ffmpeg==0.6.0
      - importlib-resources==6.5.2
      - inflect==7.5.0
      - ipython==9.7.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - jieba==0.42.1
      - jinja2==3.1.6
      - joblib==1.5.2
      - json5==0.10.0
      - julius==0.2.7
      - keras==2.9.0
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - librosa==0.10.2.post1
      - llvmlite==0.41.1
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markdown2==2.5.4
      - markupsafe==3.0.3
      - matplotlib==3.8.2
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - modelscope==1.27.0
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - msgpack==1.1.2
      - munch==4.0.0
      - networkx==3.6
      - ninja==1.13.0
      - nltk==3.9.2
      - numba==0.58.1
      - numpy==1.26.2
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - oauthlib==3.3.1
      - omegaconf==2.3.0
      - opencv-python==4.9.0.80
      - orjson==3.11.4
      - packaging==25.0
      - pandas==2.3.2
      - parso==0.8.5
      - peft==0.18.0
      - pexpect==4.9.0
      - pillow==11.3.0
      - platformdirs==4.5.0
      - pooch==1.8.2
      - proces==0.1.7
      - proglog==0.1.12
      - prompt-toolkit==3.0.52
      - protobuf==3.19.6
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pydantic==2.11.10
      - pydantic-core==2.33.2
      - pydub==0.25.1
      - pygments==2.19.2
      - pyloudnorm==0.1.1
      - pynini==2.1.6
      - pyparsing==3.2.5
      - pyphen==0.17.2
      - pystoi==0.4.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-multipart==0.0.20
      - pytorch3d==0.7.9
      - pytz==2025.2
      - pyyaml==6.0.3
      - randomname==0.2.1
      - regex==2025.11.3
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - rich==14.2.0
      - rsa==4.9.1
      - ruff==0.14.6
      - safehttpx==0.1.7
      - safetensors==0.5.2
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - semantic-version==2.10.0
      - sentencepiece==0.2.1
      - sentry-sdk==2.47.0
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - smplx==0.1.28
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soxr==1.0.0
      - stack-data==0.6.3
      - starlette==0.50.0
      - sympy==1.14.0
      - tensorboard==2.9.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - termcolor==3.2.0
      - textstat==0.7.11
      - threadpoolctl==3.6.0
      - tokenizers==0.21.0
      - tomlkit==0.13.3
      - torch==2.8.0+cu128
      - torch-stoi==0.2.3
      - torchaudio==2.8.0+cu128
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.52.1
      - triton==3.4.0
      - typeguard==4.4.4
      - typer==0.20.0
      - typer-slim==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.38.0
      - wandb==0.23.1
      - wcwidth==0.2.14
      - websockets==15.0.1
      - werkzeug==3.1.3
      - wetextprocessing==1.0.4.1
prefix: /home/shared/miniconda3/envs/zqg-indextts
